title: Ettore Delprino
author: ""
email: edelprino@gmail.com
# description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://edelprino.com" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: edelprino
github_username:  edelprino
linkedin_username: edelprino
google_analytics: UA-38378836-1

permalink: /:categories/:title:output_ext
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock