version: '3'
services: 
    jekyll:
        image: jekyll/jekyll:latest
        command: jekyll serve --watch --force_polling --verbose
        # command: bundle exec jekyll serve --watch --host 0.0.0.0
        ports: 
            - 4000:4000
        volumes: 
            - .:/srv/jekyll